1. Find the Difference
	
	You are given two strings s and t.
	String t is generated by random shuffling string s and then add one more letter at a random position.
	Return the letter that was added to t.
		
	def find_the_difference(s, t)
    s_hash = {}
  	s.each_char do |i|
  		s_hash[i].nil? ? (s_hash[i] = 0;s_hash[i] += 1) : s_hash[i] += 1
  	end

  	t_hash = {}
  	t.each_char do |j|
  		t_hash[j].nil? ? (t_hash[j] = 0;t_hash[j] += 1) : t_hash[j] += 1
  	end
    out = ''
  	t_hash.each do |k, v|
  		out = k if v > s_hash[k].to_i
  		break if v > s_hash[k].to_i
  	end
    
    return out
	end

	Scenario_1:	
		Input: s = "abcd", t = "abcde"
		Output: "e"
		Explanation: 'e' is the letter that was added.

		s = "abcd"
		t = "abcde"
		find_the_difference(s, t)

	Scenario_2:	
		Input: s = "", t = "y"
		Output: "y"

		s = ""
		t = "y"
		find_the_difference(s, t)

		def find_the_difference(s, t)
	    diff = t.chars.map(&:ord).sum - s.chars.map(&:ord).sum
	    diff.chr
		end

		def find_the_difference(s, t)
			full_str = s + t
		  ascii_vals = full_str.bytes

		  # xor_val = 0
		  # ascii_vals.each do |x|
		  #   xor_val ^= x
		  # end

		  # this can be refactored by using XOR. X ^ X = 0
		  xor_val = ascii_vals.reduce(:^)
		  xor_val.chr
		end